# note that this site.yml file is for local building and testing only
site:
  title: ownCloud Main Page
  url: https://doc.owncloud.com
  start_page: ROOT::index.adoc

content:
  sources:
  - url: .
    branches:
    - HEAD
  # note that there are no docs-xxx sources present for the test build to satisfy used references
  # we therefore have set failure_level: none, see below for more info
  # the real build is made in the docs repo using correct values

ui:
  output_dir: assets
  bundle:
    snapshot: true
    url: https://minio.owncloud.com/documentation/ui-bundle.zip

output:
  clean: true
  dir: public

asciidoc:
  attributes:
#   branch-specific-variables: 'see antora.yml'
#   build relevant
    # asciidoctor prefix for section IDs
    idprefix: ''
    idseparator: '-'
    # Antora User Interface Macros (btn, menu)
    experimental: true
    # Antora pagination (prev page, next page)
    page-pagination: true
#   common
    docs-base-url: 'https://doc.owncloud.com'
    oc-complete-base-url: 'https://download.owncloud.com/server/stable'
    oc-contact-url: 'https://owncloud.com/contact/'
    oc-help-url: 'https://owncloud.com/docs-guides/'
    oc-marketplace-url: 'https://marketplace.owncloud.com'
    oc-central-url: 'https://central.owncloud.org'
    oc-support-url: 'https://owncloud.com/support'
# note that the version attributes just need to be present and have 'next' as value
# the same applies for other repo dependent attributes as they are just here for
# local building, only change them if there are local building issues!
#
#   docs
    latest-docs-version: 'next'
    previous-docs-version: 'next'
#   server
    latest-server-version: 'next'
    previous-server-version: 'next'
    latest-server-download-version: 'next'
    current-server-version: 'next'
    oc-changelog-url: 'https://owncloud.com/changelog/server/'
    oc-install-package-url: 'https://download.owncloud.com/server/stable/?sort=time&order=asc'
    oc-examples-server-url: 'https://owncloud.install.com/owncloud'
    oc-examples-server-ip: '127.0.0.1'
    oc-examples-username: 'username'
    oc-examples-password: 'password'
    oc-complete-name: 'owncloud-complete-latest'
    occ-command-example-prefix: 'sudo -u www-data ./occ'
    occ-command-example-prefix-no-sudo: 'occ'
    php-net-url: 'https://www.php.net'
    php-supported-versions-url: 'https://www.php.net/supported-versions.php'
    http-status-codes-base-url: 'https://developer.mozilla.org/en-US/docs/Web/HTTP/Status'
    std-port-http: '8080'
    std-port-memcache: '11211'
    std-port-mysql: '3306'
    std-port-redis: '6379'
#   ocis
    latest-ocis-version: 'next'
    previous-ocis-version: 'next'
    # these versions are just for printing like in releases but not used for referencing
    ocis-actual-version: '5.0.9'
    ocis-former-version: '4.0.7'
    # Needed in docs-ocis to define which rolling release to print like in the envvars table or in deployment examples
    ocis-rolling-version: '6.4.0'
    ocis-compiled: '2024-09-12 00:00:00 +0000 UTC'
    ocis-downloadpage-url: 'https://download.owncloud.com/ocis/ocis/stable/'
#   webui
    latest-webui-version: 'next'
    previous-webui-version: 'next'
#   desktop
    latest-desktop-version: 'next'
    previous-desktop-version: 'next'
#   ios-app
    latest-ios-version: 'next'
    previous-ios-version: 'next'
#   android
    latest-android-version: 'next'
    previous-android-version: 'next'
#   branded
    latest-branded-version: 'next'
    previous-branded-version: 'next'
  extensions:
    - ./ext-asciidoc/tabs.js
    - ./ext-asciidoc/remote-include-processor.js
    - asciidoctor-kroki

antora:
  extensions:
    - ./ext-antora/generate-index.js

runtime:
  log:
    # https://docs.antora.org/antora/latest/playbook/runtime-log-failure-level/#failure-level-key
    # e.g. xrefs will report errors but building will now return 0 (ok)
    # using this prevents CI from never getting green. in antora 2, xrefs errors always returned 0
    # this is not an ideal solution and should be removed when the partial build extension (Atlas) is available
    # see: https://gitlab.com/antora/antora-atlas-extension
    # drawback, we have to (regulary) monitor the docs repo for build errors origin in docs-main via a local build.
    failure_level: none
