# note that this site.yml file is for local building and testing only
site:
  title: ownCloud Main Page
  url: https://doc.owncloud.com
  start_page: ROOT::index.adoc

content:
  sources:
  - url: .
    branches:
    - HEAD
  # note that there are no docs-xxx sources present for the test build to satisfy used references
  # we therefore have set failure_level: none, see below for more info
  # the real build is made in the docs repo using correct values

ui:
  output_dir: assets
  bundle:
    snapshot: true
    url: https://minio.owncloud.com/documentation/ui-bundle.zip

output:
  clean: true
  dir: public

asciidoc:
  attributes:
#   branch-specific-variables: 'see antora.yml'
#   global attributes loaded via antora extension
  extensions:
    - ./ext-asciidoc/tabs.js
    - ./ext-asciidoc/remote-include-processor.js
    - asciidoctor-kroki # integrated via npm

antora:
  extensions:
    - ./ext-antora/generate-index.js
    #- ./ext-antora/comp-version.js
    - require: ./ext-antora/load-global-site-attributes.js
      attributefile: https://raw.githubusercontent.com/owncloud/docs/refs/heads/master/global-attributes.yml
      #attributefile: ./global-attributes.yml
      enabled: true
    # for testing only, prints attributes used
    # use only one or the other, output can be big
    #- ./ext-antora/attributes-used-in-site-yml.js
    #- ./ext-antora/attributes-used-in-antora-yml.js

runtime:
  log:
    # https://docs.antora.org/antora/latest/playbook/runtime-log-failure-level/#failure-level-key
    # e.g. xrefs will report errors but building will now return 0 (ok)
    # using this prevents CI from never getting green. in antora 2, xrefs errors always returned 0
    # this is not an ideal solution and should be removed when the partial build extension (Atlas) is available
    # see: https://gitlab.com/antora/antora-atlas-extension
    # drawback, we have to (regulary) monitor the docs repo for build errors origin in docs-main via a local build.
    failure_level: none
